### ISSUE TITLE
Traceback when creating instance

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/client-python#58]
```
$ sf-client instance create deleteme 1 1024 -n 5489fc82-3489-44e3-83d7-bcd238417475 -d 8@cirros -d 8 -d 8
Traceback (most recent call last):
  File "/Users/mikal/virtualenvs/shakenfist/bin/sf-client", line 10, in <module>
    sys.exit(cli())
  File "/Users/mikal/src/shakenfist/client-python/shakenfist_client/main.py", line 60, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mikal/virtualenvs/shakenfist/lib/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 971, in main
    rv = self.invoke(ctx)
  File "/Users/mikal/virtualenvs/shakenfist/lib/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 1563, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mikal/virtualenvs/shakenfist/lib/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 1563, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mikal/virtualenvs/shakenfist/lib/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 1309, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mikal/virtualenvs/shakenfist/lib/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/core.py", line 715, in invoke
    return callback(*args, **kwargs)
  File "/Users/mikal/virtualenvs/shakenfist/lib/python3.7/site-packages/click-8.0.0rc1-py3.7.egg/click/decorators.py", line 23, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mikal/src/shakenfist/client-python/shakenfist_client/main.py", line 1010, in instance_create
    namespace=namespace, video=video))
  File "/Users/mikal/src/shakenfist/client-python/shakenfist_client/apiclient.py", line 279, in create_instance
    i.get('state') in ['initial', 'creating']):
AttributeError: 'list' object has no attribute 'get'
```

**Comment by mikalstill** [comment]
This is because redirection handling wasn't working correctly.
